"""add_ticket_priority

Revision ID: 14374703e4f9
Revises: pgvector_tickets
Create Date: 2026-09-11 06:56:24.328208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14374703e4f9'
down_revision = 'pgvector_tickets'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ticketpriority = sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='ticketpriority')
    ticketpriority.create(op.get_bind(), checkfirst=True)
    op.add_column('tickets', sa.Column('priority', ticketpriority, server_default='MEDIUM', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
