"""add priority_rationale to Ticket

Revision ID: 6d2f8363dfc9
Revises: 14374703e4f9
Create Date: 2026-09-14 16:05:53.035979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2f8363dfc9'
down_revision = '14374703e4f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority_rationale', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'priority_rationale')
    # ### end Alembic commands ###
