"""add document and chunk metadata

Revision ID: de3b484134cf
Revises: 5a6381fc5d41
Create Date: 2026-09-16 10:26:15.082427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b484134cf'
down_revision = '5a6381fc5d41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Add columns as nullable first to handle existing data
    op.add_column('knowledge_documents', sa.Column('document_id', sa.UUID(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('chunk_index', sa.Integer(), nullable=True))

    # 2. Backfill existing records (use id for document_id, 0 for chunk_index)
    op.execute("UPDATE knowledge_documents SET document_id = id WHERE document_id IS NULL")
    op.execute("UPDATE knowledge_documents SET chunk_index = 0 WHERE chunk_index IS NULL")

    # 3. Alter columns to NOT NULL
    op.alter_column('knowledge_documents', 'document_id', nullable=False)
    op.alter_column('knowledge_documents', 'chunk_index', nullable=False)

    # 4. Alter content type to Text and create index
    op.alter_column('knowledge_documents', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_knowledge_documents_document_id'), 'knowledge_documents', ['document_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_document_id'), table_name='knowledge_documents')
    op.alter_column('knowledge_documents', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('knowledge_documents', 'chunk_index')
    op.drop_column('knowledge_documents', 'document_id')
    # ### end Alembic commands ###
