import json
from pathlib import Path
from src.rag.chunker import chunk_article

def generate_report():
    backend_dir = Path(__file__).parent.parent
    kb_path = backend_dir / "kb_articles.json"
    
    with open(kb_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    articles = [a for a in raw if "title" in a and "content" in a][:10]

    report = [
        "# Chunker Test Output Inspection Report\n",
        "This report shows the exact 10 articles tested from `kb_articles.json` and the chunk outputs generated by `chunker.py`.\n",
        "---"
    ]

    for idx, a in enumerate(articles, 1):
        title = a["title"]
        content = a["content"]
        chunks = chunk_article(title, content, target_max_chars=1200, overlap_chars=150)
        
        report.append(f"\n## Article {idx}: {title}\n")
        report.append(f"- **Department**: `{a.get('department')}`")
        report.append(f"- **Metadata**: `{json.dumps(a.get('metadata', {}))}`")
        report.append(f"- **Original Content Length**: {len(content)} characters")
        report.append(f"- **Generated Chunk Count**: {len(chunks)}\n")

        for c in chunks:
            c_idx = c["chunk_index"]
            c_len = len(c["content"])
            report.append(f"#### Chunk {c_idx} ({c_len} characters)")
            report.append("```text")
            report.append(c["content"])
            report.append("```\n")

    report_text = "\n".join(report)

    # Save to local backend directory
    out_path = backend_dir / "chunker_test_output.md"
    with open(out_path, "w", encoding="utf-8") as f_out:
        f_out.write(report_text)

    print(f"Successfully generated chunk report at: {out_path}")

if __name__ == "__main__":
    generate_report()
